### ISSUE TITLE
What happens to the group when the meeting time is in the past date ? 

### ISSUE THREAD

**Issue by merubh** [QueppelinTech/FoxHopr#46]
When the the meeting time has gone in the past date then there is no functionality to adjust the meeting time at admin or front end side. The member will have only one option to switch group. However, previous groups would still be active in database. 

This would be causing a lot of discrepancy as a new user who signs up for BeeHopr would be shown the previous groups as well with no "Expired" status. If the member joins this group then he would be left with no other option than to change the group. 

QA team suggests that Dates should be editable  whenever admin wishes to change along with the status as Expired or Upcoming in Groups Page. 

Kindly Suggest for the same. 
![fh_bt_43](https://cloud.githubusercontent.com/assets/24872612/23021653/11dad66a-f473-11e6-8344-abc6102d7c64.png)

**Comment by jbander** [comment]
i am having a hard time understanding this issue - but that may be because i am shocked it exists (was not considered automatically by prior developers). when a meeting passes, it should clear out of the "active" system automatically. 

my understanding is that once admin adds a new meeting date/time, the meetings automatically role forward and populate every two weeks at same day/time. once a meeting has past, it should no longer be in the 'population' and available for selection during sign-up or group change. 

the data needs to be retained for reporting purposes, but not show as an available option. 

if a groups initial meeting day time is day 1 at 1pm, and on day 7O at 1pm Abhi joins (tenth week of group meeting), then he is in that group only until day 90 (when he will be reshuffled) into a new group. 

Are you sure it doesn't show because the group is still active until it the shuffle date? 

Please plan on showing us tonight. Thank you.

**Comment by jbander** [comment]
my question is - the 'group' is still live, so why can't people join it? they will simply insert into the system and automatically reshuffle accordingly with system rules. 

are you confusing past meeting time with meeting creation date?

**Comment by merubh** [comment]
Jon, We are referring to meeting date which has been done in the past not the creation date. I would be showing demo for the same for better understanding. 

Thanks

**Comment by jbander** [comment]
i am responding now via email since it appears you have done same to my original github post. please be consistent. we either need to correspond via the github thread or email only. these comments via email are not being posed to github. 

please also be prepared to discuss requirement to correct, if needed. 

going forward - post all comment and dialog to github only. 

thanks.

**Comment by merubh** [comment]
Actually Jon , all the comments posted at GITHub are send as a notification in the email box as well. So the comment i posted in GITHub was sent to your mailbox. We would be using GITHub only for doubt clarification and comments. 

Thanks

**Comment by jbander** [comment]
i went back to github and did not see your response. maybe i just don't know hot to use it. thanks.

**Comment by merubh** [comment]
This was a missing cron functionality which has been tested and closed.
